"use client";

/**
 * RRComparisonExplainer (Comparison -- all three real datasets combined)
 * --------------------------------------------------------------------
 * Trains on all three real datasets together: cardiac/ED triage,
 * NHAMCS 2021, NHAMCS 2022. Four real vitals, respiratory rate
 * genuinely measured, all banded against the official NEWS2 chart.
 * Data: data/chart-data-rr.json, generated by
 * python/generate_rr_comparison.py.
 */

import chartData from "@/data/chart-data-rr.json";
import { BarChart, GroupedBarChart, ConfusionMatrix, DecisionTreeDiagram, Histogram, STATUS_COLORS, MODEL_COLORS } from "./charts/VizCharts";

const ALL_MODEL_NAMES = ["Decision Tree", "Random Forest", "Neural Network", "XGBoost", "Transformer"];

const dtClean = chartData.scorecards.find((s) => s.dataset === "clean" && s.model === "Decision Tree")!;
const dtNoisy = chartData.scorecards.find((s) => s.dataset === "noisy" && s.model === "Decision Tree")!;
const dtKb = chartData.modelSize.find((m) => m.model === "Decision Tree")!.kb;
const rfKb = chartData.modelSize.find((m) => m.model === "Random Forest")!.kb;
const tfmKb = chartData.modelSize.find((m) => m.model === "Transformer")!.kb;
const tfmNoisy = chartData.scorecards.find((s) => s.dataset === "noisy" && s.model === "Transformer")!;

const totalRows = chartData.totalRows;
const normalPct = Math.round((chartData.classCounts[0].count / totalRows) * 1000) / 10;
const sortedFI = chartData.featureImportance.slice().sort((a, b) => b.value - a.value);
const topFeature = sortedFI[0];
const secondFeature = sortedFI[1];

const HIST_META: { key: keyof typeof chartData.histograms; label: string; unit: string }[] = [
  { key: "HR", label: "Heart rate", unit: " bpm" },
  { key: "RR", label: "Respiratory rate", unit: " br/min" },
  { key: "SpO2", label: "SpO2", unit: "%" },
  { key: "Temperature_C", label: "Temperature", unit: "°C" },
];

const SECTIONS = [
  { id: "rr1", title: "Where the data came from" },
  { id: "rr2", title: "Class distribution" },
  { id: "rr3", title: "What each vital looks like" },
  { id: "rr4", title: "The decision tree it learned" },
  { id: "rr5", title: "Confusion matrix" },
  { id: "rr6", title: "Per-class recall" },
  { id: "rr7", title: "Feature importance" },
  { id: "rr8", title: "All five models" },
  { id: "rr8b", title: "MCC score" },
  { id: "rr9", title: "Model size" },
  { id: "rr10", title: "Bottom line" },
];

export default function RRComparisonExplainer() {
  return (
    <>
      <div className="topbar">
        <div className="topbar-inner">
          <div className="brand">
            ESP32 HEALTH MONITOR &middot; <b>COMPARISON &mdash; REAL DATA, FOUR VITALS, NEWS2</b>
          </div>
        </div>
      </div>

      <div className="wrap">
        <div className="hero">
          <div className="eyebrow">Real respiratory rate, real clinical bands &mdash; no synthetic data</div>
          <h1>Comparison: all three real datasets, combined</h1>
          <p className="lede">
            All three real datasets trained together. Respiratory rate is a real measurement here, measured
            the same way the ESP32 will measure it. All four vitals are scored using the official NEWS2 chart.
          </p>
        </div>

        <div className="layout">
          <nav className="side">
            <div className="side-title">Charts</div>
            <ul className="navlist">
              {SECTIONS.map((g, i) => (
                <li key={g.id}>
                  <a href={`#${g.id}`}>
                    <span className="num">{String(i + 1).padStart(2, "0")}</span>
                    {g.title}
                  </a>
                </li>
              ))}
            </ul>
          </nav>

          <div className="sections">
            <section className="card" id="rr1">
              <h2>Three real datasets, combined</h2>
              <div className="chart-frame">
                <BarChart
                  data={[
                    { label: "Cardiac Triage", value: chartData.datasetCounts.cardiac, color: MODEL_COLORS["Decision Tree"] },
                    { label: "NHAMCS 2021", value: chartData.datasetCounts.nhamcs2021, color: MODEL_COLORS["Random Forest"] },
                    { label: "NHAMCS 2022", value: chartData.datasetCounts.nhamcs2022, color: MODEL_COLORS["Neural Network"] },
                  ]}
                />
              </div>
              <p className="simple-explain">
                {totalRows.toLocaleString()} readings total: cardiac/ED triage ({chartData.datasetCounts.cardiac.toLocaleString()}
                ), NHAMCS 2021 ({chartData.datasetCounts.nhamcs2021.toLocaleString()}), and NHAMCS 2022 (
                {chartData.datasetCounts.nhamcs2022.toLocaleString()}). Every row has a real, measured
                respiratory rate.
              </p>
            </section>

            <section className="card" id="rr2">
              <h2>Class distribution</h2>
              <div className="chart-frame">
                <BarChart data={chartData.classCounts.map((c) => ({ label: c.name, value: c.count, color: STATUS_COLORS[c.name] }))} />
              </div>
              <p className="simple-explain">
                {normalPct}% of readings are Normal. Real ED data naturally includes sick patients, so High and
                Critical show up with no artificial resampling.
              </p>
            </section>

            <section className="card" id="rr3">
              <h2>What each vital looks like</h2>
              {HIST_META.map((h) => (
                <div key={h.key} className="chart-frame" style={{ marginBottom: 18 }}>
                  <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 6 }}>{h.label}</div>
                  <Histogram
                    binEdges={chartData.histograms[h.key].binEdges}
                    counts={chartData.histograms[h.key].counts}
                    classNames={chartData.classNames}
                    unit={h.unit}
                  />
                </div>
              ))}
              <p className="simple-explain">
                Where the colors overlap, one vital alone can&apos;t tell the classes apart. That&apos;s fine
                &mdash; the model uses all four together.
              </p>
            </section>

            <section className="card" id="rr4">
              <h2>The decision tree it learned</h2>
              <div className="chart-frame">
                <DecisionTreeDiagram tree={chartData.decisionTree as any} classNames={chartData.classNames} maxDepth={3} />
              </div>
              <p className="simple-explain">
                Its first question is about <b>{chartData.decisionTree.feature}</b>. Heart rate&apos;s normal
                range under NEWS2 (51-90 bpm) is tighter than the old rule-of-thumb range, so more real
                readings now fall outside it. Respiratory rate is still the strong second question right after.
              </p>
            </section>

            <section className="card" id="rr5">
              <h2>Confusion matrix</h2>
              <div className="chart-frame">
                <ConfusionMatrix matrix={chartData.confusionMatrixNoisy} classNames={chartData.classNames} />
              </div>
              <p className="simple-explain">
                Rows are the real answer, columns are the guess. Most mistakes are between neighboring
                severity levels &mdash; the safer kind of mistake.
              </p>
            </section>

            <section className="card" id="rr6">
              <h2>Per-class recall</h2>
              <div className="chart-frame">
                <BarChart
                  data={chartData.perClassRecallNoisy.map((r) => ({ label: r.name, value: r.recall, color: STATUS_COLORS[r.name] }))}
                  valueSuffix="%"
                />
              </div>
              <p className="simple-explain">
                Critical cases are caught {chartData.perClassRecallNoisy[3].recall}% of the time, even with
                simulated sensor noise. That&apos;s the class that matters most.
              </p>
            </section>

            <section className="card" id="rr7">
              <h2>Feature importance</h2>
              <div className="chart-frame">
                <BarChart
                  data={chartData.featureImportance.map((f) => ({
                    label: f.feature,
                    value: Math.round(f.value * 1000) / 10,
                    color: f.feature === "Respiratory rate" ? "#e87ba4" : MODEL_COLORS["Decision Tree"],
                  }))}
                  valueSuffix="%"
                />
              </div>
              <p className="simple-explain">
                <b>{topFeature.feature}</b> matters most, at {Math.round(topFeature.value * 100)}%.{" "}
                {secondFeature.feature} is a clear second, at {Math.round(secondFeature.value * 100)}% &mdash;
                well ahead of SpO2 and temperature.
              </p>
            </section>

            <section className="card" id="rr8">
              <h2>All five models</h2>
              <div className="chart-frame">
                <GroupedBarChart
                  categories={ALL_MODEL_NAMES}
                  series={["clean", "noisy"].map((d) => ({
                    name: d === "clean" ? "Clean" : "Noisy (simulated sensor)",
                    color: d === "clean" ? "#2a78d6" : "#e34948",
                    values: ALL_MODEL_NAMES.map((m) => chartData.scorecards.find((s) => s.model === m && s.dataset === d)!.accuracy),
                  }))}
                  valueSuffix="%"
                />
              </div>
              <p className="simple-explain">
                Clean data looks almost perfect ({dtClean.accuracy}% for Decision Tree) because the labels come
                straight from the same rules used to score them. With noise added, all five models land close
                together.
              </p>
            </section>

            <section className="card" id="rr8b">
              <h2>MCC score</h2>
              <div className="chart-frame">
                <BarChart
                  data={ALL_MODEL_NAMES.map((m) => ({
                    label: m,
                    value: chartData.scorecards.find((s) => s.model === m && s.dataset === "noisy")!.mcc,
                    color: MODEL_COLORS[m],
                  }))}
                  decimals={3}
                />
              </div>
              <p className="simple-explain">
                MCC is a stricter accuracy check that can&apos;t be fooled by uneven class sizes. Decision Tree
                scores {dtNoisy.mcc} under noise &mdash; close to the other four, which backs up the accuracy
                numbers above.
              </p>
            </section>

            <section className="card" id="rr9">
              <h2>Model size</h2>
              <div className="chart-frame">
                <BarChart
                  data={ALL_MODEL_NAMES.map((m) => ({ label: m, value: chartData.modelSize.find((s) => s.model === m)!.kb, color: MODEL_COLORS[m] }))}
                  valueSuffix=" KB"
                  logScale
                />
              </div>
              <p className="simple-explain">
                Random Forest is {chartData.modelSizeRatio}x bigger than Decision Tree ({rfKb.toLocaleString()}{" "}
                KB vs {dtKb} KB) for about the same accuracy. The ESP32 has limited flash, so{" "}
                <b>Decision Tree is still the right choice</b>.
              </p>
            </section>

            <section className="card" id="rr10">
              <h2>Bottom line</h2>
              <p className="simple-explain">
                Across all three real datasets, <b>{topFeature.feature.toLowerCase()}</b> is the first question
                and the top feature, with {secondFeature.feature.toLowerCase()} a clear second &mdash; real
                proof that measuring it was worth it. The Transformer edges out the other four on noisy
                accuracy ({tfmNoisy.accuracy}%) and MCC ({tfmNoisy.mcc}), but Decision Tree stays small (
                {dtKb} KB vs {tfmKb} KB) and nearly as accurate ({dtNoisy.accuracy}%) under noise &mdash; still
                the practical pick for the ESP32&apos;s limited flash. One open item: SpO2 Scale 2
                doesn&apos;t apply to this use case.
              </p>
            </section>
          </div>
        </div>
      </div>
    </>
  );
}